CREATE TABLE IF NOT EXISTS crm_accounts (
id INTEGER NOT NULL,
account_name TEXT NOT NULL,
account_type INTEGER NOT NULL,
description TEXT NOT NULL,
parent_account INTEGER NOT NULL,
phone TEXT NOT NULL,
website TEXT NOT NULL,
industry INTEGER NOT NULL,
employees INTEGER NOT NULL,
billing_address TEXT NOT NULL,
billing_street TEXT NOT NULL,
billing_city TEXT NOT NULL,
billing_state TEXT NOT NULL,
billing_post_code TEXT NOT NULL,
billing_country INTEGER NOT NULL,
shipping_address TEXT NOT NULL,
shipping_street TEXT NOT NULL,
shipping_city TEXT NOT NULL,
shipping_state TEXT NOT NULL,
shipping_post_code TEXT NOT NULL,
shipping_country INTEGER NOT NULL,
assign_to INTEGER NOT NULL,
created_at DATETIME,
created_by INTEGER NOT NULL,
updated_at DATETIME,
updated_by INTEGER NOT NULL,
deleted_at DATETIME,
deleted_by INTEGER NOT NULL,
project_id INTEGER NOT NULL,
valid INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS crm_activities (
id INTEGER NOT NULL,
activity_name TEXT NOT NULL,
activity_link TEXT NOT NULL,
activity_icon TEXT NOT NULL,
search_url TEXT NOT NULL,
sl_no INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS crm_contacts (
Id INTEGER NOT NULL,
account_id INTEGER NOT NULL,
name_title INTEGER NOT NULL,
first_name TEXT NOT NULL,
last_name TEXT NOT NULL,
Surname TEXT NOT NULL,
Designation TEXT NOT NULL,
Department TEXT NOT NULL,
full_address TEXT NOT NULL,
Street TEXT NOT NULL,
City TEXT NOT NULL,
State TEXT NOT NULL,
post_code TEXT NOT NULL,
Country INTEGER NOT NULL,
Mobile TEXT NOT NULL,
office_phone TEXT NOT NULL,
Fax TEXT NOT NULL,
Website TEXT NOT NULL,
Email TEXT NOT NULL,
Industry INTEGER NOT NULL,
Note TEXT NOT NULL,
nature_id INTEGER NOT NULL,
Image TEXT NOT NULL,
assign_to INTEGER NOT NULL,
created_at DATETIME,
created_by INTEGER NOT NULL,
updated_at DATETIME,
updated_by INTEGER NOT NULL,
deleted_at DATETIME,
deleted_by INTEGER NOT NULL,
project_id INTEGER NOT NULL,
Valid INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS crm_leads (
Id INTEGER NOT NULL,
generated_lead_id TEXT NOT NULL,
csv_id INTEGER NOT NULL,
csv_file INTEGER NOT NULL,
name_title INTEGER NOT NULL,
first_name TEXT NOT NULL,
last_name TEXT NOT NULL,
Surname TEXT NOT NULL,
Designation TEXT NOT NULL,
Department TEXT NOT NULL,
full_address TEXT NOT NULL,
Street TEXT NOT NULL,
City TEXT NOT NULL,
State TEXT NOT NULL,
post_code TEXT NOT NULL,
Country INTEGER NOT NULL,
Mobile TEXT NOT NULL,
office_phone TEXT NOT NULL,
Fax TEXT NOT NULL,
Website TEXT NOT NULL,
Email TEXT NOT NULL,
company_name TEXT NOT NULL,
Industry INTEGER NOT NULL,
Employees INTEGER NOT NULL,
lead_description TEXT NOT NULL,
Rating INTEGER NOT NULL,
lead_source INTEGER NOT NULL,
Campaign INTEGER NOT NULL,
lead_referred_by TEXT NOT NULL,
assign_to INTEGER NOT NULL,
step_one_status INTEGER NOT NULL,
step_one_date DATETIME,
step_two_status INTEGER NOT NULL,
step_two_date DATETIME,
step_three_status INTEGER NOT NULL,
step_three_date DATETIME,
step_four_status INTEGER NOT NULL,
step_four_date DATETIME,
step_five_status INTEGER NOT NULL,
step_five_date DATETIME,
Stage INTEGER NOT NULL,
created_at DATETIME,
created_by INTEGER NOT NULL,
updated_at DATETIME,
updated_by INTEGER NOT NULL,
deleted_at DATETIME,
deleted_by INTEGER NOT NULL,
project_id INTEGER NOT NULL,
Valid INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS crm_lead_info_basic (
Id INTEGER NOT NULL,
generated_lead_id TEXT NOT NULL,
csv_id INTEGER NOT NULL,
csv_file INTEGER NOT NULL,
first_name TEXT NOT NULL,
last_name TEXT NOT NULL,
Designation TEXT NOT NULL,
Department TEXT NOT NULL,
company_name TEXT NOT NULL,
full_address TEXT NOT NULL,
lead_email TEXT NOT NULL,
lead_mobile TEXT NOT NULL,
lead_office_phone TEXT NOT NULL,
Website TEXT NOT NULL,
lead_source INTEGER NOT NULL,
lead_source_description TEXT NOT NULL,
lead_referred_by TEXT NOT NULL,
lead_description TEXT NOT NULL,
assign_to INTEGER NOT NULL,
Status INTEGER NOT NULL,
created_at DATETIME,
created_by INTEGER NOT NULL,
updated_at DATETIME,
updated_by INTEGER NOT NULL,
deleted_at DATETIME,
deleted_by INTEGER NOT NULL,
project_id INTEGER NOT NULL,
Valid INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS crm_lead_opportunities (
Id INTEGER NOT NULL,
lead_id INTEGER NOT NULL,
lead_opportunities_status INTEGER NOT NULL,
lead_opportunities_description TEXT NOT NULL,
lead_category INTEGER NOT NULL,
currency_id INTEGER NOT NULL,
lead_opportunities_amount REAL NOT NULL,
Probability REAL NOT NULL,
created_at DATETIME,
created_by INTEGER NOT NULL,
updated_at DATETIME,
updated_by INTEGER NOT NULL,
deleted_at DATETIME,
deleted_by INTEGER NOT NULL,
project_id INTEGER NOT NULL,
Valid INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS crm_lead_products (
Id INTEGER NOT NULL,
lead_id INTEGER NOT NULL,
product_id INTEGER NOT NULL,
created_at DATETIME,
created_by INTEGER NOT NULL,
updated_at DATETIME,
updated_by INTEGER NOT NULL,
deleted_at DATETIME,
deleted_by INTEGER NOT NULL,
project_id INTEGER NOT NULL,
Valid INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS crm_lead_source (
Id INTEGER NOT NULL,
source_name TEXT NOT NULL,
created_at DATETIME,
created_by INTEGER NOT NULL,
updated_at DATETIME,
updated_by INTEGER NOT NULL,
deleted_at DATETIME,
deleted_by INTEGER NOT NULL,
project_id INTEGER NOT NULL,
Valid INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS crm_opportunities (
Id INTEGER NOT NULL,
account_id INTEGER NOT NULL,
opportunity_name TEXT NOT NULL,
opportunity_type INTEGER NOT NULL,
opportunity_source INTEGER NOT NULL,
campaign_source INTEGER NOT NULL,
budget_confirmed INTEGER NOT NULL,
analysis_completed INTEGER NOT NULL,
Status INTEGER NOT NULL,
Category INTEGER NOT NULL,
step_one_status INTEGER NOT NULL,
step_one_date DATETIME,
step_two_status INTEGER NOT NULL,
step_two_date DATETIME,
step_three_status INTEGER NOT NULL,
step_three_date DATETIME,
step_four_status INTEGER NOT NULL,
step_four_date DATETIME,
step_five_status INTEGER NOT NULL,
step_five_date DATETIME,
step_final_status INTEGER NOT NULL,
step_final_date DATETIME,
Stage INTEGER NOT NULL,
Probability INTEGER NOT NULL,
currency_id INTEGER NOT NULL,
opportunity_amount REAL NOT NULL,
proposed_amount REAL NOT NULL,
actual_amount REAL NOT NULL,
closed_date DATE NOT NULL,
lost_reason_id INTEGER NOT NULL,
lost_reason_details TEXT NOT NULL,
assign_to INTEGER NOT NULL,
created_at DATETIME,
created_by INTEGER NOT NULL,
updated_at DATETIME,
updated_by INTEGER NOT NULL,
deleted_at DATETIME,
deleted_by INTEGER NOT NULL,
project_id INTEGER NOT NULL,
Valid INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS crm_opportunity_contact (
Id INTEGER NOT NULL,
opportunity_id INTEGER NOT NULL,
contact_id INTEGER NOT NULL,
role_id INTEGER NOT NULL,
is_primary INTEGER,
created_at DATETIME,
created_by INTEGER NOT NULL,
updated_at DATETIME,
updated_by INTEGER NOT NULL,
deleted_at DATETIME,
deleted_by INTEGER NOT NULL,
project_id INTEGER NOT NULL,
Valid INTEGER NOT NULL
);